### ISSUE TITLE
兄弟有往年题和复习资料不？

### ISSUE THREAD

**Issue by GuanLiliang** [linkedlist771/Random-Process-HW#1]
搜随机过程搜到你的项目了，好巧我也在上孙应飞老师的随机过程课。马上期末考试了，兄弟有资料参考一下不😭人要寄了

**Comment by GuanLiliang** [comment]
我只有12年的试卷
<html xmlns:x="tencent"><style type='text/css'></style><body>
通过百度网盘分享的文件：随机过程 201…链接:https://pan.baidu.com/s/1k1zFHlQMOn2MAJtoXc24vw?pwd=6rc2 提取码:6rc2复制这段内容打开「百度网盘APP 即可获取」
--


</body></html>通过百度网盘分享的文件：随机过程 201…
链接[:https://pan.baidu.com/s/1k1zFHlQMOn2MAJtoXc24vw?pwd=6rc2](https://github.com/linkedlist771/Random-Process-HW/issues/:https://pan.baidu.com/s/1k1zFHlQMOn2MAJtoXc24vw?pwd=6rc2) 
提取码:6rc2
复制这段内容打开「百度网盘APP 即可获取」

**Comment by linkedlist771** [comment]
抱歉刚看到，1我找到了19年的试卷但是没有答案，链接我挂一下:
[19年试卷](http://alist.dingli.life/%E5%B8%B8%E7%94%A8%E6%96%87%E4%BB%B6/%E9%9A%8F%E6%9C%BA%E8%BF%87%E7%A8%8B2019-2020%E7%9C%9F%E9%A2%98.pdf)

**Comment by GuanLiliang** [comment]
万分感谢！就指着最后一个星期突击了(✿◡‿◡)
